---
- name: Create instances
  os_server:
    cloud: openstack
    name: "{{ item.0.name }}"
    image: "{{ item.0.image }}"
    key_name: "{{ item.0.key_name }}"
    flavor: "{{ item.0.flavor }}"
    security_groups: "{{ item.0.security_group }}"
    delete_fip: yes
    wait: no
    nics:
      - net-name: int_network
    meta: "group={{ item.1.group }}, deployment_name={{ item.1.deployment_name }}"
    userdata: |
      #!/bin/bash
      cat /root/openstack.pub >> /home/cloud-user/.ssh/authorized_keys
  with_subelements: 
    - "{{ osp_servers }}"
    - meta

- name: Add floating IP to instance
  os_floating_ip:
    cloud: openstack
    state: present
    reuse: yes
    server: "{{ item.value.name }}"
    network: ext_network
    wait: true
    timeout: 200
  with_dict: "{{ osp_servers }}"


# tasks file for osp.servers
